<?php

namespace Database\Seeders;

use App\Models\AnimationsGenres;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AnimationsGenresSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $animeGenres =
        [
            [
                'animation_id'=>'1',
                'genre_id'=>'18',
            ],
            [
                'animation_id'=>'1',
                'genre_id'=>'8',
            ],
            [
                'animation_id'=>'1',
                'genre_id'=>'3',
            ],
            [
                'animation_id'=>'1',
                'genre_id'=>'2',
            ],
            [
                'animation_id'=>'1',
                'genre_id'=>'1',
            ],
            [
                'animation_id'=>'2',
                'genre_id'=>'2',
            ],
            [
                'animation_id'=>'2',
                'genre_id'=>'5',
            ],
            [
                'animation_id'=>'2',
                'genre_id'=>'8',
            ],
            [
                'animation_id'=>'2',
                'genre_id'=>'9',
            ],
            [
                'animation_id'=>'3',
                'genre_id'=>'8',
            ],
            [
                'animation_id'=>'3',
                'genre_id'=>'18',
            ],
            [
                'animation_id'=>'4',
                'genre_id'=>'18',
            ],
            [
                'animation_id'=>'4',
                'genre_id'=>'13',
            ],
            [
                'animation_id'=>'4',
                'genre_id'=>'12',
            ],
            [
                'animation_id'=>'4',
                'genre_id'=>'1',
            ],
            [
                'animation_id'=>'5',
                'genre_id'=>'12',
            ],
            [
                'animation_id'=>'5',
                'genre_id'=>'15',
            ],
            [
                'animation_id'=>'5',
                'genre_id'=>'8',
            ],
            [
                'animation_id'=>'5',
                'genre_id'=>'19',
            ],
            [
                'animation_id'=>'5',
                'genre_id'=>'18',
            ],
            [
                'animation_id'=>'6',
                'genre_id'=>'5',
            ],
            [
                'animation_id'=>'6',
                'genre_id'=>'1',
            ],
            [
                'animation_id'=>'6',
                'genre_id'=>'3',
            ],
            [
                'animation_id'=>'6',
                'genre_id'=>'2',
            ],
            [
                'animation_id'=>'6',
                'genre_id'=>'11',
            ],
            [
                'animation_id'=>'7',
                'genre_id'=>'13',
            ],
            [
                'animation_id'=>'7',
                'genre_id'=>'14',
            ],
            [
                'animation_id'=>'7',
                'genre_id'=>'7',
            ],
            [
                'animation_id'=>'8',
                'genre_id'=>'10',
            ],
            [
                'animation_id'=>'8',
                'genre_id'=>'4',
            ],
            [
                'animation_id'=>'9',
                'genre_id'=>'5',
            ],
            [
                'animation_id'=>'9',
                'genre_id'=>'7',
            ],
            [
                'animation_id'=>'9',
                'genre_id'=>'3',
            ],
            [
                'animation_id'=>'9',
                'genre_id'=>'12',
            ],
            [
                'animation_id'=>'10',
                'genre_id'=>'19',
            ],
            [
                'animation_id'=>'10',
                'genre_id'=>'2',
            ],
            [
                'animation_id'=>'10',
                'genre_id'=>'15',
            ],
            [
                'animation_id'=>'11',
                'genre_id'=>'16',
            ],
            [
                'animation_id'=>'11',
                'genre_id'=>'17',
            ],
            [
                'animation_id'=>'12',
                'genre_id'=>'5',
            ],
            [
                'animation_id'=>'12',
                'genre_id'=>'6',
            ],
            [
                'animation_id'=>'12',
                'genre_id'=>'8',
            ],
            [
                'animation_id'=>'13',
                'genre_id'=>'13',
            ],
            [
                'animation_id'=>'13',
                'genre_id'=>'10',
            ],
            [
                'animation_id'=>'13',
                'genre_id'=>'9',
            ],
            [
                'animation_id'=>'14',
                'genre_id'=>'2',
            ],
            [
                'animation_id'=>'14',
                'genre_id'=>'18',
            ],
            [
                'animation_id'=>'14',
                'genre_id'=>'8',
            ],
            [
                'animation_id'=>'14',
                'genre_id'=>'6',
            ],
            [
                'animation_id'=>'15',
                'genre_id'=>'6',
            ],
            [
                'animation_id'=>'15',
                'genre_id'=>'18',
            ],
            [
                'animation_id'=>'15',
                'genre_id'=>'7',
            ],
            [
                'animation_id'=>'16',
                'genre_id'=>'2',
            ],
            [
                'animation_id'=>'16',
                'genre_id'=>'2',
            ],
            [
                'animation_id'=>'16',
                'genre_id'=>'1',
            ],
            [
                'animation_id'=>'17',
                'genre_id'=>'3',
            ],
            [
                'animation_id'=>'17',
                'genre_id'=>'4',
            ],
            [
                'animation_id'=>'18',
                'genre_id'=>'8',
            ],
            [
                'animation_id'=>'18',
                'genre_id'=>'19',
            ],
            [
                'animation_id'=>'18',
                'genre_id'=>'18',
            ],
        ];
        foreach ($animeGenres as $animeGenre){
            AnimationsGenres::insert($animeGenre);
        }
    }
}
