<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ActorRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            //
            'first_name'=>'required|min:2|max:50',
            'last_name'=>'required|min:2|max:50',
            'father_name'=>'max:50',
            'birth'=>'required',
        ];
    }
    public function messages()
    {
        return [
            'first_name.required'=>'Имя не может быть пустым',
            'birth'=>'Дата не может быть пустым',
            'first_name.min'=>'Имя слишком короткое(более 2 букв)',
            'first_name.max'=>'Имя слишком длинное',
            'last_name.required'=>'Фамилия не может быть пустым',
            'last_name.min'=>'Фамилия слишком короткое(более 2 букв)',
            'last_name.max'=>'Фамилия слишком длинное',
            'father_name.max'=>'Отчество слишком длинное',


        ];
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
