<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class AnimationRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            //
            'name'=>'required|min:4|max:50',
            'description'=>'required|min:4',
        ];
    }
    public function messages()
    {
        return [
            'name.required'=>'Название не может быть пустым',
            'name.min'=>'Название слишком короткое(более 4 букв)',
            'name.max'=>'Название слишком длинное',
            'description.required'=>'Описание не может быть пустым',
            'description.min'=>'Описание слишком короткое',
            'description.max'=>'Описание слишком длинное',
        ];
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
