<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class GenresRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        //зарегистрированный пользователь
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            //
            'name'=>'required|min:4|max:25|unique:genres'
        ];
    }
    public function messages()
    {
        return [
            'name.required'=>'Поле "Название" не может быть пустым',
            'name.min'=>'Поле должно содержать более 4 букв',
            'name.max'=>'Маx значения поле превысино',
            'name.unique'=>'Значение должно быть уникальным',
        ];
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
