<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StudioRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        //        false-не может отправлять данные пока не авторизован
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            //
            'name'=>'required|min:4|max:50|unique:studios'
        ];
    }
    public function messages()
    {
        return [
            'name.required'=>'Поле "Название" не может быть пустым',
            'name.min'=>'Название слишком короткое(более 4 букв)',
            'name.max'=>'Название слишком длинное',
            'name.unique'=>'Название должно быть уникальным',

        ];
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
